### ISSUE TITLE
第十期 ( 2019-01-07 / 2019-01/13 )

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#10]
第十期在下面回复

**Comment by mehooo** [comment]
推荐文章：[再聊移动端页面的适配](https://www.w3cplus.com/css/vw-for-layout.html)
投稿理由：移动端web适配方案（手淘解决方案）；布局采用vw单位，通过相应的依赖转化成px，并可以成比例适配大小。
投稿人：Darcy.cao

**Comment by xiangrenya** [comment]
推荐文章：[GraphQL 初探—面向未来 API 及其生态圈](https://zhuanlan.zhihu.com/p/30701842)
推荐理由：GraphQL 是由 Facebook 开源的查询语言，对 API 中的数据提供了一套易于理解的完整描述，使得客户端能够准确地获得它需要的数据，而且没有任何冗余，也让 API 更容易地随着时间推移而演进，还能用于构建强大的开发者工具。
投稿人：Allen.Xiang

**Comment by maningXu** [comment]
推荐文章：https://www.jianshu.com/p/574506bef2e4
推荐理由：每日都在使用的，import，export，export default ，今天就来好好介绍一下这些命令。
投稿人：Maning.Xu

**Comment by juanhuang99** [comment]
推荐文章：[IndexedDB：浏览器端数据库](http://www.ruanyifeng.com/blog/2018/07/indexeddb.html)
推荐理由：IndexedDB 是一个用于在浏览器中储存较大数据结构的 Web API，并提供索引功能以实现高性能查找。像其他基于 SQL 的 关系型数据库管理系统 (RDBMS) 一样，IndexedDB 是一个事务型的数据库系统。然而，它是使用 JavaScript 对象而非列数固定的表格来储存数据的。
投稿人：Jane Huang

**Comment by zhuchuanlei** [comment]
推荐工具: [imgcook 由设计稿一键智能生成代码的大厨](https://imgcook.taobao.org/)
推荐理由: 此工具是新鲜货。在生成代码时合理运用了Flex。
推荐人: Peter Zhu

**Comment by lichangwei** [comment]
推荐文章：[如果你想走得快，一个人走；如果想走得远，选择一些人一起走](https://mp.weixin.qq.com/s/u-D2c6LfGPJqPE6hqg9hRA)
推荐理由：一点感悟，分享给大家。

**Comment by kingller** [comment]
推荐文章: [JavaScript 代码简洁之道](https://juejin.im/post/5c24b7a851882509a76875e8)
推荐理由: 代码质量与其整洁度成正比。干净的代码，既在质量上较为可靠，也为后期维护、升级奠定了良好基础。本文并不是代码风格指南，而是关于代码的可读性、复用性、扩展性探讨。

**Comment by beenle-xiaojie** [comment]
文章：[点击劫持踩坑](https://beenle-xiaojie.github.io/2019/01/07/ClickJacking/)
理由：最近做了一个点击劫持的安全配置，踩坑过程分享给大家

**Comment by Aliennnnnn** [comment]
推荐文章: [TCP建立连接过程中为什么需要“三次握手”](https://aliennnnnn.github.io/2019/01/09/three-way-handshake/)
推荐理由: TCP 为什么是三次握手，而不是两次或四次？之前对此一直是模模糊糊，最近在看这方面的知识，把看到的一些比较好的解释和最近的一些理解组织一下和大家交流分享一下。
