### ISSUE TITLE
第十一期 ( 2019-01-14 / 2019-01/20 )

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#11]
第十一期在下面回复

**Comment by fansgithub** [comment]
网址：https://fansgithub.github.io/2019/01/08/%E7%90%86%E8%A7%A3%E6%89%A7%E8%A1%8C%E4%B8%8A%E4%B8%8B%E6%96%87%E5%92%8C%E4%BD%9C%E7%94%A8%E5%9F%9F/
投稿理由：理解js执行上下文和作用域
投稿人：kasa..fan

网址：https://fansgithub.github.io/2019/01/18/%E6%89%8B%E5%86%99%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84Promise/
投稿理由：代码实战，手写一个简单的Promise函数
投稿人：kasa..fan

**Comment by xiangrenya** [comment]
推荐文章：[JavaScript 代码简洁之道](https://juejin.im/post/5c24b7a851882509a76875e8)
推荐理由：代码质量与其整洁度成正比。干净的代码，既在质量上较为可靠，也为后期维护、升级奠定了良好基础。
投稿人：Allen.Xiang

**Comment by mehooo** [comment]
推荐文章：[互联网协议入门（一）](http://www.ruanyifeng.com/blog/2012/05/internet_protocol_suite_part_i.html) [互联网协议入门（二）](http://www.ruanyifeng.com/blog/2012/06/internet_protocol_suite_part_ii.html)
推荐理由：上海的某一块网卡送出信号，洛杉矶的另一块网卡居然就收到了，两者实际上根本不知道对方的物理位置，你不觉得这是很神奇的事情吗？从2个相反的方向解释了互联网的原理，通俗易懂。
投稿人：Darcy.cao

**Comment by Aliennnnnn** [comment]
推荐文章：[详解 Webpack 之 externals 的使用](https://aliennnnnn.github.io/2019/01/18/externals/)
推荐理由：介绍最近项目在做的资源加载优化中使用的externals是如何使用的。
投稿人：Cotton.Wang

**Comment by beenle-xiaojie** [comment]
推荐文章：[localStorage存取对象数组](https://beenle-xiaojie.github.io/2019/01/15/localStorage/)
推荐理由：localStorage只能存储字符，在需要存储对象数组时需要进行转换。

**Comment by G-Grant** [comment]
推荐文章: [也谈部分渲染](https://juejin.im/post/5c4432a4f265da615e05bc39)
推荐理由: 当列表成千上万时，部分渲染就显得尤其重要。这篇文章带你了解一个最简单的部分渲染是如何进行实现的。
投稿人: Barret

**Comment by caojing1126** [comment]
推荐文章: [漫话：如何给女朋友解释什么是并发和并行](https://juejin.im/post/5bdf0667e51d450b267fe3e3)
推荐理由: 并发与并行是很重要的两个容易混淆的操作系统的知识点，这篇文章会很形象的帮助你理解这两个概念。
投稿人: Amy Cao
