### ISSUE TITLE
第十二期 ( 2019-01-21 / 2019-01/27 )

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#12]
第十二期在下面回复

**Comment by G-Grant** [comment]
## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX

**Comment by yomizhong** [comment]
网址：[pug之传入文本换行问题](https://yomizhong.github.io/2019/01/18/pug%E4%B9%8B%E4%BC%A0%E5%85%A5%E6%96%87%E6%9C%AC%E7%9A%84%E6%8D%A2%E8%A1%8C%E9%97%AE%E9%A2%98/#more)
投稿理由：本文分享pug接收文本参数的换行问题
投稿人：yomi zhong

**Comment by kingller** [comment]
网址：[javascript模块化之CommonJS、AMD、CMD、UMD、ES6](https://blog.csdn.net/Real_Bird/article/details/54869066)
投稿理由：这是一篇关于js模块化编程的总结，解释了各模块化规范的区别。

**Comment by kingller** [comment]
网址：[webpack之打造Javascript类库](https://www.jianshu.com/p/e30f83120fcc)
投稿理由：最近有个需求，需要将组件库打包为类库，提供给各项目使用，优化各项目切换时的资源加载，但是又不想影响我们在程序中的写法。这是一篇关于如何利用webpack打造自己的Javascript库的文章。

**Comment by kingller** [comment]
网址：[webpack之外部资源和模块引用使用方式切换](https://www.jianshu.com/p/8bf56b49c4fd)
投稿理由：上一篇文章我们讲到了如何打造自己的Javascript类库。接下来我们发现使用外部资源引用方式后，修复一些bug和新增一些功能必须要等到下一版本发布，在项目中才能使用，而且修改类库后本地运行的代码无法即时刷新，影响我们的开发效率，于是我们又想在开发时把我们的外部资源引用方式切换回模块引用。

**Comment by cqazsxer** [comment]
网址: [浏览器野史 UserAgent列传](http://litten.me/2014/09/26/history-of-browser-useragent/)
投稿理由:  为什么Chrome的userAgent信息会有其他厂商的标识? 这篇文章带你了解userAgent的前世今生。

**Comment by katrina-ZhangZiYue** [comment]
网址：[一篇文章构建你的 NodeJS 知识体系](https://juejin.im/post/5c4c0ee8f265da61117aa527)
投稿理由: 在学习Node.js的过程中，一直有一种杂乱无章的感觉。这篇文章，将Node中的主要模块一一讲述，带你构建你的Node知识体系。
