### ISSUE TITLE
第十三期 ( 2019-01-28 / 2019-02-11 )

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#13]
## 第十三期在下面回复

**请务必填写投稿人**

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX

**Comment by maningXu** [comment]
网址：https://www.jianshu.com/p/d7ff1fb055b7
投稿理由：了解RESTful风格，才能在定义接口时更加的规范、标准；对于不合理的接口，可以根据规范，更好的进行反驳。
投稿人：Maning.Xu

**Comment by yomizhong** [comment]
网址：[文档流与浮动](https://yomizhong.github.io/2019/01/25/%E6%96%87%E6%A1%A3%E6%B5%81%E4%B8%8E%E6%B5%AE%E5%8A%A8/#more)
投稿理由：本文分享文档流与浮动及浮动引起的父元素高度塌陷解决
投稿人：yomi zhong

**Comment by legu2009** [comment]
推荐文章：[通过页面空闲时预加载加快页面访问](https://blog.bitsrc.io/faster-page-loads-by-prefetching-links-during-idle-time-5abe42dacf9)
推荐理由：功能点实现起来都比较简单，主要使新api的使用和思路。
投稿人：locker.gu
