### ISSUE TITLE
第十四期（2019-02-12 / 2019-02-18）

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#14]
## 第十四期在下面回复
**请务必填写投稿人**

## 投稿格式
* 网址：XX
* 投稿理由：XX
* 投稿人：XX

**Comment by lichangwei** [comment]
* 网址：[SSH 免密登录远程主机](https://lichangwei.github.io/2019/02/11/ssh-wihtout-password/)
* 投稿理由：你是不是有个记事本，上面记着各种服务器的账号和密码，每次登录服务器时都要翻一下这个记事本，本文会告诉你一种方法让你告别这种痛苦。
* 投稿人：Louis

**Comment by maningXu** [comment]
* 网址：https://www.jianshu.com/p/52fa21e7474f
* 投稿理由：掌握这些简单常用的 git 命令，利于快速提高开发速度哦；并且，该文档将会持续更新一些简单的 git 命令，完全可以当作一个查阅手册。
* 投稿人：Maning

**Comment by maningXu** [comment]
* 网址：[Git 之分支管理](https://www.jianshu.com/p/52fa21e7474f)
* 投稿理由：掌握这些简单常用的 git 命令，利于快速提高开发速度哦；并且，该文档将会持续更新一些简单的 git 命令，完全可以当作一个查阅手册。
* 投稿人： Maning

**Comment by G-Grant** [comment]
* 网址：[搭建基于 Mac 的 Flutter 开发环境](https://github.com/G-Grant/Note/issues/1)
* 投稿理由：主要讲解搭建一个 Flutter 开发环境遇到的坑与解决办法
* 投稿人：Barret
