### ISSUE TITLE
第十五期(2019-02-19 / 2019-02-25)

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#15]
## 第十五期在下面回复
**请务必填写投稿人**

## 投稿格式
* 网址：XX
* 投稿理由：XX
* 投稿人：XX

**Comment by legu2009** [comment]
推荐文章：[Monaco Editor 使用入门](https://www.cnblogs.com/legu/p/10350090.html)
推荐理由：vscode使用的代码编辑器，自己整理的所以推荐下。
投稿人：locker.gu

**Comment by mehooo** [comment]
推荐文章：[捋一捋React的生命周期](https://segmentfault.com/a/1190000018216610)
推荐理由：16.3之前的生命周期和16.4之后的生命周期,详细对比说明（有图）
投稿人：Darcy.Cao

**Comment by zhuchuanlei** [comment]
推荐文章: [parseInt 详解](https://zhuchuanlei.github.io/blog/parseInt/)
推荐理由: 文章通过一个例子，详细介绍了parseInt两个参数的规则。
投稿人: Peter Zhu
