### ISSUE TITLE
第十六期(2019-02-26 / 2019-03-04)

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#16]
## 第十六期在下面回复
**请务必填写投稿人**

## 投稿格式
* 网址：XX
* 投稿理由：XX
* 投稿人：XX

**Comment by maningXu** [comment]
* 网址：[SQL 基础](https://www.jianshu.com/p/13999e9cdefb)
* 投稿理由：简单的一些数据操作语言，巩固一下SQL 的基础知识；有利于接口沟通，理解后台口中的一些 “update”，“全删”，“全插”，大致做了怎么样的操作。
* 投稿人：Maning.Xu

**Comment by zhuchuanlei** [comment]
网址：[延迟加载 React Components](https://mp.weixin.qq.com/s/Bi2nZNFGJZ1a9MfpKIuG4g)
投稿理由：改善应用性能，构建更好的用户体验
投稿人：Peter Zhu

**Comment by lichangwei** [comment]
网址：[如何快速找到 Nginx 配置文件？](https://lichangwei.github.io/2019/02/25/where-is-my-nginx-config-file/)
投稿理由：告诉你怎样快速找到Nginx配置文件在哪里，并且稍加扩展介绍一种能够快速找到某一任意文件在哪里的方法。
投稿人：Louis Li

**Comment by legu2009** [comment]
网址：[阿里为大家学习Flutter操碎了心](https://mp.weixin.qq.com/s/JvlTnZJGSESpPEwYJF1XNg)
投稿理由：有同事准备今年学习Flutter，推荐下这篇文章，希望有帮助。
投稿人：Locker Gu

**Comment by caojing1126** [comment]
网址：[为什么我认为数据结构与算法对前端开发很重要？](https://mp.weixin.qq.com/s/2NJbxrUqxOupFeEQiS-rRg)
投稿理由：文章通过一些实际的开发例子来让你意识到数据结构与算法对前端开发者的重要性。
投稿人：Amy Cao

**Comment by kingller** [comment]
网址：[网易前端开发工程师公开课](https://study.163.com/course/introduction/1209072812.htm)
投稿理由：听了下，挺不错的，分享给大家
投稿人：Kingller.Tang
