### ISSUE TITLE
第十七期（2019-03-05 / 2019-03-11）

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#17]
## 第十七期在下面回复
**请务必填写投稿人**

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX

**Comment by G-Grant** [comment]
+ [[译] 使用 Render props 吧！](https://juejin.im/post/5a3087746fb9a0450c4963a5)
+ 投稿理由：我们已经这么使用了，但是还需要了解出现的背景。如果你想学习 React Hooks 的话，先看一下 React Hooks 出现的原因是什么也很不错。
+ 投稿人: Barret Ge

**Comment by lichangwei** [comment]
- 网址：[如何从 WordPress 中导入文章到数据库中](https://lichangwei.github.io/2019/03/05/import-posts-from-wordpress/)
- 投稿理由：本文是对当前一个任务的总结，涉及网络爬虫相关技术，涉及阿里云OSS的使用。
- 投稿人：Louis Li

**Comment by legu2009** [comment]
- 网址：[UI知识小游戏](https://cantunsee.space/)
- 投稿理由：考验审美，设计功力的网页小游戏。设计师版本的“找茬游戏”
- 投稿人：Locker Gu

**Comment by zhuchuanlei** [comment]
网址：[从一个数组中找出 N 个数，其和为 M 的所有可能--最 nice 的解法](https://juejin.im/post/5c81d543f265da2deb6ad691)
投稿理由：二进制和位运算确实是较优的组合，你会想到吗利用该组合解题？估计很多人对着两个知识比较陌生了，有空时再熟悉一下吧。
投稿人：Peter Zhu

**Comment by katrina-ZhangZiYue** [comment]
网址：[ES6的异步处理](https://juejin.im/post/5c8495bbe51d457eea0aaf6f)
投稿理由： 在学习ES6的过程中，最困惑的就是promise。如何理解它，会用它，才是最终的目的。
投稿人： Katrina Zhang
