### ISSUE TITLE
第十八期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#18]
## 第十八期在下面回复
**请务必填写投稿人**

## 投稿格式
+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX
+ 是否个人: 是

**Comment by G-Grant** [comment]
+ 网址：[【译】Javascript中的不变性（Immutability in JavaScript）](https://zhuanlan.zhihu.com/p/31193499)
+ 投稿理由：在函数式编程中，不可变性是一个核心原则，同时也在面向对象编程中使用。在这篇文章中，我会介绍不可变性到底是什么，在Javascript中如何使用这一概念， 以及它为什么是有用的。
+ 投稿人：Barret Ge
+ 是否个人: 否

**Comment by maningXu** [comment]
网址：[正则基础](https://www.jianshu.com/p/77d5961463e3)
投稿理由：正则基础回顾。
投稿人：Maning.Xu
是否个人: 是

**Comment by yomizhong** [comment]
网址：[字符串正则匹配多个类名](https://yomizhong.github.io/2019/03/08/%E5%AD%97%E7%AC%A6%E4%B8%B2%E6%AD%A3%E5%88%99%E5%8C%B9%E9%85%8D%E5%A4%9A%E4%B8%AA%E7%B1%BB%E5%90%8D/#more)
投稿理由：分享从html文件中正则匹配出所有类名
投稿人：yomi.zhong
是否个人：是

**Comment by lichangwei** [comment]
网址：[生命的密度](https://lichangwei.github.io/2019/03/15/density-of-life/)
投稿理由：前些天坐火车去了一趟广州，记录了一点点感想。并且提醒大家在很多较大的火车站都有站内换乘通道，对于需要换乘的乘客，可以免去出站进展又一次安检的繁琐步骤。
投稿人： Louis Li
是否个人: 是

**Comment by katrina-ZhangZiYue** [comment]
网址： [浏览器文件下载](https://juejin.im/post/5c8a2b9bf265da2ddd4aa117)
投稿理由： 实现浏览器下载的几种方式
投稿人： Katrina Zhang
是否个人:  是
