### ISSUE TITLE
第十九期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#19]
## 第十九期在下面回复

请务必填写投稿人

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by yomizhong** [comment]
网址：[edm邮件制作总结](https://yomizhong.github.io/2019/03/20/edm%E9%82%AE%E4%BB%B6%E5%88%B6%E4%BD%9C%E6%80%BB%E7%BB%93/#more)
投稿理由：本文分享edm邮件制作的一些规范及注意事项
投稿人：yomi.zhong
是否个人：是

**Comment by maningXu** [comment]
网址：[面向对象程序设计-对象](https://www.jianshu.com/p/06f5d2e2b623);
投稿理由：理解对象，理解创建对象的几种方式，理解一些曾经困扰人的原型的知识点。
投稿人：Maning Xu
是否个人: 是

**Comment by katrina-ZhangZiYue** [comment]
网址：[ES6的模块化](https://juejin.im/post/5c97496bf265da61103b4f3e)
投稿理由：使用import非常简单，但是背后是怎么实现的呢？为什么有时候用require，有时候用import呢？通过这篇文章，我们就先来了解一下ES6中的模块化。
投稿人：Katrina Zhang
是否个人: 是

**Comment by cqazsxer** [comment]
网址: [编写有弹性的组件](https://overreacted.io/zh-hans/writing-resilient-components)
投稿理由: 通过良好的配置，linter 是一个很好的工具，它可以在 bug 出现前就能发现它们。但它对代码风格的关注过多，使其变得会分散注意力。如果遵循严格的风格指南是一种分心，那到底什么才是重要的呢？这就是这篇文章的主题。
投稿人: Tony Gao
是否个人: 否
