### ISSUE TITLE
第二期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#2]
第二期在此下面回复

**Comment by lichangwei** [comment]
**推荐文章：** [技术雷达第19期](https://www.thoughtworks.com/cn/radar)
**推荐理由：** 技术雷达旨在洞察构建未来的技术和趋势，帮助我们跟上技术潮流，可以通过[这个页面](https://www.thoughtworks.com/cn/radar/faq)了解更多。在最新一期中，推荐了很多技术，比如用于检查Git仓库中是否包含敏感信息的[git-secrets](https://github.com/awslabs/git-secrets)，用于测试的[testcafe](https://devexpress.github.io/testcafe/)，还有大家熟悉的[Prettier](https://prettier.io/)，[VS Code](https://code.visualstudio.com/)，[VS Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack)，[TypeScript](https://www.typescriptlang.org/)等等。相信大家一定能够从中找到感兴趣的技术或工具。

**Comment by fansgithub** [comment]
推荐文章：[nginx常用功能](https://mp.weixin.qq.com/s/IRhxdg_cgkJQoSLiHooRsg)
推荐理由：高性能、高并发的轻量级服务器，百度、京东、新浪、网易、腾讯、淘宝网站的选择。了解一些网站部署的基础知识，别仅限于前端。

**Comment by fansgithub** [comment]
推荐文章： [Performance API](http://javascript.ruanyifeng.com/bom/performance.html)
推荐理由：W3C推出的一套性能API标准，简化开发者对网站性能进行精确分析与控制的过程，方便开发者采取手段提高web性能。

**Comment by legu2009** [comment]
推荐文章： [WebAssembly’s post-MVP future: A cartoon skill tree](https://hacks.mozilla.org/2018/10/webassemblys-post-mvp-future/)
推荐理由：WebAssembly技术很高端，从firefox提出asm.js算起，也有几年了。平时前端开发虽然涉及不到，多了解一些，看看js如何改变世界。

**Comment by kingller** [comment]
推荐文章： [图解浏览器的工作原理](https://zhuanlan.zhihu.com/p/47407398)
推荐理由：可能每一个前端工程师都想要理解浏览器的工作原理。这篇文章可以帮助我们了解从在浏览器地址栏中输入 url 到页面展现的短短几秒内浏览器究竟做了什么；平时常常听说的各种代码优化方案是究竟为什么能起到优化的作用；更细化的了解浏览器的渲染流程。

**Comment by caojing1126** [comment]
推荐文章：[看看这些被同事喷的JS代码风格你写过多少](https://juejin.im/post/5becf928f265da61380ec986)
推荐理由：针对我们经常说的代码规范问题，比如变量相关，函数相关，语法等，文章给出了一些具体的实用的对比和解决方案，可以很直观的帮助你解决代码规范的问题。

**Comment by katrina-ZhangZiYue** [comment]
推荐文章：[写给前端开发者不一样的VSCode配置](https://juejin.im/post/5bea48c4e51d454e5b5f19e8)
推荐理由：对于不是很了解VSCode的前端新人来说，这篇文章详细全面的告诉你，拥有这些配置的VSCode是多么强大。检查拼写错误，提取js和ts到单独模块，一键添加console.*，创建，复制，移动，重命名和删除文件和目录的便捷方式......，总有一款适合你。

**Comment by G-Grant** [comment]
第二期投稿截止
