### ISSUE TITLE
第二十期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#20]
## 第二十期在下面回复
**请务必填写投稿人**

## 投稿格式
+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by lichangwei** [comment]
网址：[为什么要引入 BFF](https://lichangwei.github.io/2019/03/25/why-bff)
投稿理由：本文介绍了BS架构发展历程，当前主流前后端分离模式及其弊端，最后介绍了为什么BFF是一种更好的方案。
投稿人：Louis Li
是否个人: 是

**Comment by yomizhong** [comment]
网址：[jquery 获取及修改文本元素的内容](https://yomizhong.github.io/2019/03/26/jquery%20%E8%8E%B7%E5%8F%96%E5%8F%8A%E4%BF%AE%E6%94%B9%E6%96%87%E6%9C%AC%E5%85%83%E7%B4%A0%E7%9A%84%E5%86%85%E5%AE%B9/#more)
投稿理由：本文分享使用html()、text()的回调函数来修改元素内容的方法
投稿人：yomi zhong
是否个人：是

**Comment by katrina-ZhangZiYue** [comment]
网址：[sitemap详解](https://juejin.im/post/5ca1676c6fb9a05e5f3cffdc)
投稿理由：sitemap是什么？我们的网站为什么需要生成sitemap文件？对于搜索引擎优化，我们可以做什么？这篇文章带你来初步了解一下。
投稿人：Katrina Zhang
是否个人：是

**Comment by legu2009** [comment]
网址：[如果我是一线技术主管……](https://mp.weixin.qq.com/s/M68FGx0tp5WHks46H_6HfQ)
投稿理由：工作中，向上管理和向下管理都很重要，博文中提到的一些点，我觉得都可以学习。
投稿人：Locker Gu
是否个人：不是

**Comment by xiangrenya** [comment]
网址：[BigPipe的应用](https://www.jianshu.com/p/f59b4633840d)
投稿理由：使用 bigpipe 方案，减少首屏显示时间，提高大型复杂页面的性能加速，提升用户体验。在 node 中间层的基础上，实现 bigpipe 方案，通过 node 层请求多个接口，获取数据，然后分块传输给客户端，可以有效地解决页面出现大量 api 请求，消耗网络传输时间，以及并发限制带来的请求阻塞和滞后等问题。
投稿人：Allen Xiang
是否个人: 是

**Comment by mehooo** [comment]
推荐文章：[常见六大Web [安全攻防解析]](https://segmentfault.com/a/1190000018073845)
投稿理由：在互联网时代，数据安全与个人隐私受到了前所未有的挑战，各种新奇的攻击技术层出不穷。如何才能更好地保护我们的数据？本文主要侧重于分析几种常见的攻击的类型以及防御的方法。
投稿人：Darcy.cao
是否个人：不是
