### ISSUE TITLE
第二十二期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#22]
## 第二十二期在下面回复
**请务必填写投稿人**

## 投稿格式
+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by legu2009** [comment]
网址：[数据结构和算法 可视化](https://www.cs.usfca.edu/~galles/visualization/Algorithms.html)
投稿理由：强烈推荐下，准备学习数据结构和算法的。虽然页面UI差了些，但是功能还是很强大。
投稿人：Locker Gu
是否个人: 否

**Comment by mehooo** [comment]
网址：[你不知道的浏览器页面渲染机制](https://segmentfault.com/a/1190000018811208?_ea=9441025)
投稿理由：以 Webkit 为例，对现代浏览器的渲染过程进行一个深度的剖析。
投稿人：Darcy cao
是否个人: 否

**Comment by lichangwei** [comment]
网址：[想提高决策的效率？试试 DACI 框架](https://lichangwei.github.io/2019/04/10/daci-desicion-framework/)
投稿理由：相信大家都遇到这样的情况，拉了一堆人开会讨论一个问题，整个过程热火朝天，会议也一再拖延，但是最后还是没有结论。有没有什么方法能够改善这个状态呢？我今天就给大家介绍一个Atlassian提出的一种方案：DACI框架。
投稿人：Louis Li
是否个人: 是

**Comment by yomizhong** [comment]
网址：[从认识webpack.config.js开始](https://yomizhong.github.io/2019/04/09/%E4%BB%8E%E8%AE%A4%E8%AF%86webpack-config-js%E5%BC%80%E5%A7%8B/#more)
投稿理由：本文分享对webpack配置文件的学习记录
投稿人：yomi zhong
是否个人：是

**Comment by katrina-ZhangZiYue** [comment]
网址：[Sequelize详解](https://juejin.im/post/5cb3ea6ce51d456e896349d4)
投稿理由：使用node如何直接连接数据库来完成一些操作？Sequelize帮助你实现。
投稿人：Katrina Zhang
是否个人：是
