### ISSUE TITLE
第二十三期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#23]
## 第二十三期在下面回复
**请务必填写投稿人**

## 投稿格式
+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by maningXu** [comment]
网址：[关于移动端的长按事件](https://www.jianshu.com/p/118686a6126d)
投稿理由：移动端的长按事件
投稿人：Maning Xu
是否个人: 是

**Comment by katrina-ZhangZiYue** [comment]
网址：[开发一个npm包，你会吗？](https://juejin.im/post/5cb83353518825327c24dc85)
投稿理由：开发一个npm包的流程
投稿人：Katrina Zhang
是否个人: 是

**Comment by yomizhong** [comment]
网址：[table-cell实现等高布局](https://yomizhong.github.io/2019/04/22/table-cell%E5%B8%83%E5%B1%80/#more)
投稿理由：分享table-cell实现等高布局的方法
投稿人：yomi zhong
是否个人：是

**Comment by yomizhong** [comment]
网址：[table-cell实现等高布局](https://yomizhong.github.io/2019/04/22/table-cell%E5%B8%83%E5%B1%80/#more)
投稿理由：分享table-cell实现等高布局的方法
投稿人：yomi zhong
是否个人：是

**Comment by lichangwei** [comment]
网址：[使用 Shell 实现服务的监控和重启](https://lichangwei.github.io/2019/04/18/monitor-shell/)
投稿理由：我们的NPM私有仓库时不时会挂掉，暂时没有找到好的方案从根本上解决，所以就写了一个守护进程来自动检测服务状态并在挂掉时重启服务。本文就介绍了如何使用 Shell 编写守护程序。
投稿人：Louis Li
是否个人: 是
