### ISSUE TITLE
第二十四期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#24]
## 第二十四期在下面回复

**请务必填写投稿人**

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by katrina-ZhangZiYue** [comment]
网址：[#!/usr/bin/env node 到底是什么？](https://juejin.im/post/5cb93cd651882578b148c637)
投稿理由：在npm包的index.js的文件第一行有这样一段代码`#!/usr/bin/env node`，它到底是什么？这篇文章来为大家解答一下这个疑惑。
投稿人：Katrina Zhang
是否个人: 是

**Comment by maningXu** [comment]
网址：[由SetTimeout引发的](https://www.jianshu.com/p/cd6c397578d4)
投稿理由：了解setTimeout，Promise的代码执行先后顺序；
投稿人：Maning Xu
是否个人: 是

**Comment by yomizhong** [comment]
网址：[纯css画三角形](https://yomizhong.github.io/2019/04/26/%E7%BA%AFcss%E7%94%BB%E4%B8%89%E8%A7%92%E5%BD%A2/#more)
投稿理由：本文分享使用css画三角形及实现对话框效果
投稿人：yomi zhong
是否个人：是

**Comment by yomizhong** [comment]
网址：[使用css画三条横线的菜单栏图标](https://yomizhong.github.io/2019/04/26/%E4%BD%BF%E7%94%A8css%E7%94%BB%E4%B8%89%E6%9D%A1%E6%A8%AA%E7%BA%BF%E7%9A%84%E8%8F%9C%E5%8D%95%E6%A0%8F%E5%9B%BE%E6%A0%87/#more)
投稿理由：本文分享css实现三条横线的两种画法
投稿人：yomi zhong
是否个人：是

**Comment by yomizhong** [comment]
网址：[img图片定宽高不变形裁剪](https://yomizhong.github.io/2019/04/26/img%E5%9B%BE%E7%89%87%E5%AE%9A%E5%AE%BD%E9%AB%98%E4%B8%8D%E5%8F%98%E5%BD%A2%E8%A3%81%E5%89%AA/#more)
投稿理由：本文分享object-fit属性的应用
投稿人：yomi zhong
是否个人：是
