### ISSUE TITLE
第二十五

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#25]
## 第二十五期在下面回复

**请务必填写投稿人**

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by zhuchuanlei** [comment]
网址：https://zhuchuanlei.github.io/blog/function/
投稿理由：通过js代码执行顺序说明了字面量函数和普通函数声明的差异。
投稿人：Peter Zhu
是否个人: 是

**Comment by katrina-ZhangZiYue** [comment]
网址：[npm包全局安装和局部安装,执行包命令有什么不同？](https://juejin.im/post/5ccf9dc0f265da03914d7524)
投稿理由：npm包全局安装和局部安装,执行包命令有什么不同?
投稿人：Katrina Zhang
是否个人: 是
