### ISSUE TITLE
二十六期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#26]
## 第二十六期在下面回复

**请务必填写投稿人**

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by lichangwei** [comment]
网址：[如何正确地使用电子邮件](https://lichangwei.github.io/2019/04/28/how-to-write-a-good-email/)
投稿理由：我经常会收到一些邮件，要么标题词不达意，要么收件人，抄送人混淆，要么英文标点后没有空格等格式错误。我们该怎么写一封格式正确的电子邮件，请花3分钟阅读此文吧。
投稿人：Louis Li
是否个人: 是

**Comment by maningXu** [comment]
网址：[border-radius圆角边框](https://www.jianshu.com/p/45de13332931)
投稿理由：border-radius的详细介绍；
投稿人：Maning Xu
是否个人: 是
