### ISSUE TITLE
第二十七期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#27]
## 第二十七期在下面回复

**请务必填写投稿人**

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by lichangwei** [comment]
网址：[如何编写模拟数据](https://lichangwei.github.io/2019/05/12/mock-server/)
投稿理由：我们要求每个前端项目都要手动编写模拟数据，这篇文章介绍了为什么要编写模拟数据，以及如何编写模拟数据。
投稿人：Louis Li
是否个人: 是
