### ISSUE TITLE
第二十八期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#28]
## 第二十八期在下面回复

**请务必填写投稿人**

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by maningXu** [comment]
网址：[RegExp对象](https://www.jianshu.com/p/57504a3dee23)
投稿理由：RegExp对象；
投稿人：Maning Xu
是否个人: 是

**Comment by G-Grant** [comment]
+ 网址: [论时间数组去除交叉重复项](https://juejin.im/post/5ce7b70ef265da1bb77643d2)
+ 投稿理由: 近日，接到个紧急需求，考勤员给员工排班，但是这个员工当天有请假时间段，有休息时间段，有用餐时间段。
+ 投稿人: Barret Ge
+ 是否个人: 是

**Comment by G-Grant** [comment]
+ 网址: [Index as a key is an anti-pattern](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318)
+ 投稿理由: 为什么用数组索引作为 Key 是一个反模式。
+ 投稿人: Barret Ge
+ 是否个人: 否
