### ISSUE TITLE
第二十九期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#29]
## 第二十九期在下面回复

**请务必填写投稿人**

## 投稿格式

+ 网址：XX
+ 投稿理由：XX
+ 投稿人：XX（比如：Bar Sui）
+ 是否个人: 是

**Comment by maningXu** [comment]
网址：[Git 之标签管理](https://www.jianshu.com/p/9b02c07fdcc7)
投稿理由：如何给分支打标签，看了其实都是一些简单的命令。
投稿人：Maning Xu
是否个人: 是

**Comment by zhuchuanlei** [comment]
网址：[ECharts 保存图片](https://zhuchuanlei.github.io/blog/echarts-save-image/)
投稿理由：ECharts 保存图片有配置可以直接用，但是保存Icon是在canvas内部的。本文介绍了怎么将ECharts配置的Icon与非ECharts配置的Icon放在一起。
投稿人：祝传磊
是否个人: 是

**Comment by G-Grant** [comment]
@zhuchuanlei 推荐人以你 github 马甲来命名了😆
