### ISSUE TITLE
第三期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#3]
第三期请在下面回复

**Comment by G-Grant** [comment]
+ 推荐文章: [Web长列表的救星？谷歌推出Virtual Scroller](https://mp.weixin.qq.com/s/uhqEqoESeBZ13kl6OEc9KQ)
+ 推荐理由: 在刚刚结束的 Chrome dev summit 2018 上，谷歌工程经理 Gray Norton 向我们介绍 virtual-scroller，一个 Web 滚动组件，未来它可能会成为 Web 高层级 API（Layered API）的一部分。它的目标是解决长列表的性能问题，消除离屏渲染。该项目处于研发中，你可以在 GitHub 查看它的开发者预览版本。

**Comment by G-Grant** [comment]
+ 推荐文章: [HTTP/3](https://juejin.im/post/5be977c96fb9a04a0a5eb6f5)
+ 推荐理由: HTTP/3 来啦，你还在等什么？赶紧了解一下

**Comment by zhuchuanlei** [comment]
**推荐文章:** [你所不知道的 CSS 阴影技巧与细节](http://www.cnblogs.com/coco1s/p/9913885.html?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io)
**推荐理由:** 众多logo中，抖音的logo相对较炫，你会想到什么方式实现呢？这篇文章讲诉了一些CSS阴影的运用，同时给出了以一个元素画出抖音logo的方式。

**Comment by lichangwei** [comment]
**推荐文章**：[2018 年 JavaScript 生态圈调查报告出炉！](https://www.infoq.cn/article/HS9HANIdb5SU_tINr1HA)
**推荐理由**：文章末尾有英文[原版链接](https://2018.stateofjs.com/introduction/)。文章很短，自己阅读。有意思的是实用程序库中前8名中竟然有3个是关于时间的。

**Comment by maningXu** [comment]
网址：https://www.jianshu.com/p/17d0bc7f9390
投稿理由：在控制台输入name属性时，发现无论怎么赋值，显示name类型为string。因此进行的一个小知识总结。
投稿人：Maning
