### ISSUE TITLE
第三十期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#30]
## 第三十期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by mehooo** [comment]
网址：https://segmentfault.com/a/1190000018701596
投稿理由：[把HTML转成PDF的4个方案及实现](https://segmentfault.com/a/1190000018701596)
投稿人：Darcy cao
是否个人: 否

**Comment by kingller** [comment]
网址：[迁移React项目至typescript](https://www.jianshu.com/p/967a9a79b9af)
投稿理由：如何迁移自己的项目至TypeScript
投稿人：Kingller Tang
是否个人: 是

**Comment by kingller** [comment]
网址：[ESLint+Prettier统一TypeScript代码风格](https://www.jianshu.com/p/fed0fbf95172)
投稿理由：如何使用ESLint + Prettier来统一我们的前端代码风格
投稿人：Kingller Tang
是否个人: 是
