### ISSUE TITLE
第三十一期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#31]
## 第三十一期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by G-Grant** [comment]
* 网址：[让你的网页更丝滑（全）](https://mp.weixin.qq.com/s/wHb65dZxA8qEKhEF91Ko7g)
* 投稿理由：这篇文章是2019年5月11号，作者在上海FDConf2019上的分享整理。
* 投稿人：Barret
 * 是否个人: 否

**Comment by lichangwei** [comment]
- 网址：[集中地声明 TypeScript 类型](https://lichangwei.github.io/2019/06/13/declare-file-in-typescript/)
- 投稿理由：本文介绍了一种在项目中声明业务模型类型的一种最佳实践，也介绍了如何声明`window`对象上的全局变量的方法。
- 投稿人：Louis Li
- 是否个人：是

**Comment by maningXu** [comment]
网址：[ES6-Symbol](https://www.jianshu.com/p/07bf89b5348a)
投稿理由：关于Symbol的简单介绍
投稿人：Maning Xu
是否个人: 是

**Comment by G-Grant** [comment]
* 网址：[How To Use The React Context API](https://medium.com/flatiron-labs/how-to-use-the-react-context-api-70a76d3974d5)
* 投稿理由：如果您最近听过很多关于新的React Context API并希望了解更多信息，那么这篇文章就是为您准备的。
* 投稿人：Barret
 * 是否个人: 否
