### ISSUE TITLE
第三十二期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#32]
## 第三十二期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by PiersZhang** [comment]
+ 网址：[Mac下利用Charles抓包以及https请求unknow](https://www.jianshu.com/p/2d83dbc13057)
+ 投稿理由：很多移动端开发过程中，需要集成在三方app中，此时不能用chrome调试，可以用青花瓷抓取到网络数据
+ 投稿人：piers.zhang
+ 是否个人: 是

**Comment by lichangwei** [comment]
- 网址：[在浏览器和 Node Server 之间加密敏感信息](https://lichangwei.github.io/2019/06/18/crypto-password-between-browser-and-node-server/)
- 投稿理由：前些天安全组的同事给官网项目报安全Issue说密码字段没有加密，这篇文章描述了如何在Node项目中实现前后端敏感信息加密。
- 投稿人：Louis
- 是否个人: 是

**Comment by maningXu** [comment]
网址：[优化你的JavaScript条件语句](https://www.jianshu.com/p/a1ec63a9603e)
投稿理由：优化你的JavaScript条件语句的几种方式；
投稿人：Maning Xu
是否个人: 是

**Comment by G-Grant** [comment]
@PiersZhang 注意格式啊

**Comment by G-Grant** [comment]
@maningXu 注意格式啊，可以通过复制我发的格式快速使用
