### ISSUE TITLE
第三十五期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#35]
## 第三十五期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by maningXu** [comment]
* 网址：[ES6-Promise](https://www.jianshu.com/p/d2f61e8795d2)
* 投稿理由：关于 Promise 的知识点总结
* 投稿人：Maning Xu
* 是否个人: 是

**Comment by shadow88sky** [comment]
* 网址:[Flutter入门集](https://www.jianshu.com/p/2f9ed303c8ec)  
* 投稿理由: 跟一把潮流，实现自己做个App的梦想  
* 投稿人: Chen Xu  
* 是否个人: 是

**Comment by lichangwei** [comment]
- 网址: [Nginx 指令 try_files 使用方法](https://lichangwei.github.io/2019/07/15/nginx-try-files/)
- 投稿理由: 本文介绍了如何通过Nginx的try_files指令将多个目录或站点合并成起来形成统一服务。
- 投稿人:  Louis Li
- 是否个人: 是
