### ISSUE TITLE
第三十六期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#36]
## 第三十六期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by MonkeyInWind0** [comment]
网址：https://www.jianshu.com/p/aa341475bf61
投稿理由：翻文档整理的笔记，第一篇对官方demo每行代码做了介绍，之后每篇一个组件，不是很深入，但是适合初学者。
投稿人：Monid Pei
是否个人： 是

**Comment by mehooo** [comment]
网址： [Lodash 严重安全漏洞背后 你不得不知道的 JavaScript 知识](https://zhuanlan.zhihu.com/p/73186974)
投稿理由：关键字-原型污染。
投稿人：Darcy cao
是否个人： 否

**Comment by kingller** [comment]
网址：[迁移React项目至TypeScript（babel版）](https://www.jianshu.com/p/ad5831aca286)
投稿理由：由于TypeScript与ECMAScript装饰器编译出的代码不同，这里阐述了如何用babel来配置TypeScript项目。（TypeScript项目看这篇）
投稿人：Kingller Tang
是否个人: 是

**Comment by kingller** [comment]
网址：[JavaScript编码规范](http://wiki.gaiaworks.cn:8090/pages/viewpage.action?pageId=42143515)
投稿理由：虽然我们已经有eslint和prettier来帮助我们统一编码风格了，但我们还是需要了解下我们现在使用的编码规范是什么，这可以帮助我们更好的完成编码。（注：需在内网访问）
投稿人：Kingller Tang

**Comment by kingller** [comment]
网址：[如何配置React项目直接使用TypeScript包（babel版）](https://www.jianshu.com/p/0f857b3c30ef)
投稿理由：我们的组件库已经改成了TypeScript，但很多项目还在使用JavaScript，所以这里来说说怎么在我们JavaScript版的React项目中直接使用TypeScript的包。（JavaScript项目看这篇）
投稿人：Kingller Tang
是否个人: 是

**Comment by shadow88sky** [comment]
网址: [Nest-Graphql使用](https://www.jianshu.com/p/d3d8b861afa6)
投稿理由: Graphql天然适配BFF层，在Nest中又不需要额外学习成本，为何不来学习一波?
投稿人: Chen Xu
是否个人:是
