### ISSUE TITLE
第三十八期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#38]
## 第三十八期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by yomizhong** [comment]
网址：[webpack项目本地正常运行，但打包报错问题排查](https://yomizhong.github.io/2019/08/08/webpack%E6%89%93%E5%8C%85%E5%87%BA%E9%94%99%EF%BC%8Cnpm-start%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C/#more)
投稿理由：本文分享webpack在打包过程中遇到的问题
投稿人：yomi zhong
是否个人: 是

**Comment by G-Grant** [comment]
* 网址：[解读 Babel 编译后的 decorator 代码](https://juejin.im/post/5d4eadab6fb9a06b0b1c6586)
* 投稿理由：decorator 虽然现在还没有定稿，但是现在十分流行。你是否想知道在类上加 decorator 与属性上加 decorator 的区别，这篇文章就有这个讲解。
* 投稿人：Barret Ge
 * 是否个人: 是

**Comment by luoruihuan** [comment]
* 网址：[input 调用相机和HTML5 getUserMedia API 实现图片的拍照加水印功能](https://luoruihuan.top/2019/08/11/%E5%AE%9E%E7%8E%B0%E5%9B%BE%E7%89%87%E7%9A%84%E6%8B%8D%E7%85%A7%E5%8A%A0%E6%B0%B4%E5%8D%B0%E5%8A%9F%E8%83%BD/)
* 投稿理由：梳理了移动端，前端Canvas处理图片加水印容易遇到的坑和解决方法，包括图片压缩和一些ios10一下问题的兼容处理。
* 投稿人：Ron Luo
* 是否个人: 是
