### ISSUE TITLE
第三十九期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#39]
## 第三十九期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by G-Grant** [comment]
- 网址：[Mobx 源码初探 - observable（一）](https://juejin.im/post/5d541e5ef265da03f3334b8f)
- 投稿理由：想不想知道 `@observable` 背后所做的事情，来看看吧
- 投稿人：Barret Ge
- 是否个人: 是

**Comment by yomizhong** [comment]
网址：(https://yomizhong.github.io/2019/08/12/typeScript学习记录/#more)[typeScript学习记录]
投稿理由：分享typescript入门学习的基本语法
投稿人：Yomi Zhong
是否个人：是

**Comment by yomizhong** [comment]
网址：[typeScript学习记录](https://yomizhong.github.io/2019/08/12/typeScript学习记录/#more)
投稿理由：分享typescript入门学习的基本语法
投稿人：Yomi Zhong
是否个人：是
