### ISSUE TITLE
第四期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#4]
第四期在下面回复

**Comment by zhuchuanlei** [comment]
**推荐文章**: [2019年前端面试都聊啥？一起来看看](https://mp.weixin.qq.com/s/e-IC588SZPJK2QRBm3KuHA)
**推荐文章**: 要使一场面试成功，必须对其进行讨论。它必须是一个交换思想的地方。它应该引发人们思考并客观地分析给定的问题。它要能帮助我们理解人们做决策的过程。它要能帮助我们了解一个人对技术和解决问题的热情。它意味着要了解未来可能的同事。所有那些谜题，tricks 或 typeof null 都不能真正称为面试。

**Comment by kingller** [comment]
**推荐文章:** [JavaScript 的 this 指向问题深度解析](https://mp.weixin.qq.com/s/xMLZLQzb2CBvkB7HkiNzSA)
**推荐理由:** 这篇文章很清晰的分析了this机制，可以帮助我们秒懂this，减少日常开发中经常会遇到的this指向问题。

**Comment by caojing1126** [comment]
**推荐文章:** [柯里化函数应用](https://mp.weixin.qq.com/s/jd5xVj-ajDLtdCaJwJFTdw)
**推荐理由:** 文章中针对：兼容浏览器时间监听方法、防抖和节流、兼容低版本IE的bind方法三个场景案例来全面介绍柯里化函数，希望能帮助大家理解柯里化。

**Comment by lichangwei** [comment]
**推荐文章**：[NetFlix：只能做到称职的员工，也要拿钱走人](https://mp.weixin.qq.com/s/Kso02eGRdOqkPNna1BBCLg)
**推荐理由**：NetFlix 公司在2009年释出了一份100多页的PPT，讲述Netflix的企业文化精髓：自由和责任。这份PPT在网上被查阅超过了600万次，甚至被Facebook公司的COO桑德伯格称为“硅谷最重要的文件”。原PPT文件[下载地址](https://github.com/singpenguin/ppt/blob/master/Netflix%20Culture:Freedom%20%26%20Responsibility.pptx)。

**Comment by katrina-ZhangZiYue** [comment]
推荐文章：[css3新增属性—第一讲](https://juejin.im/post/5c03df495188250e8601f4ac)
推荐理由：在静态网页中，需要自己来写大量的css。如何提高代码质量，来复习一下css3，回顾那些被你抛在脑后的属性吧。（这是我自己写的第一篇文章，不足之处，敬请各位大神多多批评指正）
