### ISSUE TITLE
第四十期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#40]
## 第四十期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by G-Grant** [comment]
- 网址：[Object.observe is dead. Long live MobX.observe](https://medium.com/@mweststrate/object-observe-is-dead-long-live-mobservable-observe-ad96930140c5)
- 投稿理由：Object.observe 已死，Mobx.observe 长存
- 投稿人： Barret Ge
- 是否个人: 否

**Comment by G-Grant** [comment]
- 网址：[Becoming fully reactive: an in-depth explanation of MobX](https://medium.com/hackernoon/becoming-fully-reactive-an-in-depth-explanation-of-mobservable-55995262a254)
- 投稿理由：深入了解 Mobx
- 投稿人： Barret Ge
- 是否个人: 否

**Comment by yomizhong** [comment]
网址：[图标字体制作](https://yomizhong.github.io/2019/07/04/woff%E5%9B%BE%E6%A0%87%E5%AD%97%E4%BD%93%E5%88%B6%E4%BD%9C/#more)
投稿理由：本文分享图标字体制作方法以及制作过程中可能遇到的问题
投稿人：Yomi Zhong
是否个人: 是
