### ISSUE TITLE
第四十一期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#41]
## 第四十一期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by ezzhu** [comment]
- 网址：http://zjhweb.com/blog/?p=378

- 投稿理由：从ifconfig浅谈IP

- 投稿人：Ethan Zhu

- 是否个人：是

**Comment by lichangwei** [comment]
网址：[在 Jenkins 中添加企业微信通知](https://lichangwei.github.io/2019/08/29/jenkins-qywx-notification/)
投稿理由：在企业微信群里添加机器人通知消息，以最快速度掌握Jenkins构建任务状态。不再焦急地盯着进度条，而是静候佳音，“叮咚”，构建成功啦。
投稿人： Louis Li
是否个人: 是
