### ISSUE TITLE
第四十二期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#45]
## 第四十二期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by mehooo** [comment]
网址：[响应式图片srcset全新释义sizes属性w描述符](https://www.zhangxinxu.com/wordpress/2014/10/responsive-images-srcset-size-w-descriptor/)
投稿理由：响应式布局三大概念之一弹性图片
投稿人：Darcy cao
是否个人: 否

**Comment by yomizhong** [comment]
网址：[模版引擎pug入门](https://yomizhong.github.io/2019/09/06/pug%E5%85%A5%E9%97%A8/#more)
投稿理由： 分享模版引擎pug的基本语法规则
投稿人： Yomi Zhong
是否个人： 是
