### ISSUE TITLE
第五期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#5]
第五期在下面回复

**Comment by legu2009** [comment]
推荐文章：[构建时预渲染：网页首帧优化实践](https://tech.meituan.com/first_contentful_paint_practice.html)
推荐理由：首帧优化是个老掉牙的话题，通过博文可以学习相关知识，现有方案对比。美团技术通过无头浏览器，webpak打包的预渲染的方式实现SSR的效果，提供了新的思路。

**Comment by legu2009** [comment]
推荐文章：[前端码农之蜕变 — AST(抽象语法树)](https://github.com/CodeLittlePrince/blog/issues/19#issue-384220522)
推荐理由：现在很多库都是依赖AST实现的，相关的插件也需要对AST一定的了解。有时间可以先了解一下相关的概念，知道我们还能做什么。精通了AST，甚至可以创造自己的语言。

**Comment by zhangzhike** [comment]
推荐文章：[ES6的Symbol类型](https://juejin.im/post/5bdbb3406fb9a022752c319e)
推荐理由：Symbol是es6中的一种类型，平常很少接触，更别提使用了，希望此文介绍之后，可以在实际的项目中使用。

**Comment by maningXu** [comment]
推荐文章：https://www.jianshu.com/p/9e652f90c1c0
推荐理由：由于ajax进行了非常良好的封装，在某次自己封装的方法传输数据时，传输数据一直显示【object，object】，才了解到自己遗忘的知识点。因此进行了一次巩固。

**Comment by fansgithub** [comment]
推荐文章：https://mp.weixin.qq.com/s/yyvmUMyVdrew9QGtIOcXhA
推荐理由：如果女友问你双11当天为什么不能申请退款？不知道的话就来了解一下！

**Comment by kingller** [comment]
推荐文章：[微软官方实锤来了！拥抱 Chromium 做桌面浏览器](https://mp.weixin.qq.com/s/Qj7ij4qYcfhXd_LnbLKu9w)
推荐理由：微软计划采用 Chromium 开源项目，开发 Edge 桌面浏览器。前端童鞋么有望不再处理IE兼容。

**Comment by kingller** [comment]
推荐文章：[关于Http协议，你必须要知道的](https://segmentfault.com/a/1190000016751071)
推荐理由：正如标题所说，关于Http协议，你必须要知道的。

**Comment by caojing1126** [comment]
推荐文章：[如何开始一个微信小程序](https://www.jianshu.com/p/fe3691805ed5)
推荐理由：微信小程序现在逐步成为互联网界的网红，一个轻量级的应用，用完即走是它的口号，了解JavaScript你就可以拥有一个自己的小程序啦，快来体验一下吧！

**Comment by zhuchuanlei** [comment]
推荐文章: [看看这些被同事喷的JS代码风格你写过多少](https://github.com/jackiewillen/blog/issues/14)
推荐理由: 虽然已经有校验工具来保证代码规范，总是依靠第三方，不如养成良好的编码习惯。

**Comment by beenle-xiaojie** [comment]
推荐文章: [git bisect 二分法快速定位问题代码](https://beenle-xiaojie.github.io/2018/12/21/git-bisect/)
推荐理由:Git提供的bisect这一命令,就是二分法查找快速地在提交中定位 Bug,少则几次,多则十几次就会定位到引入Bug的提交.

**Comment by miumiumius** [comment]
推荐文章: [初探 Webpack 性能优化](https://aliennnnnn.github.io/2018/12/20/webpack-per/)
推荐理由: Webpack是现在主流的功能强大的模块化打包工具，在使用Webpack时，如果不注意性能优化，有非常大的可能会产生性能问题.

**Comment by Aliennnnnn** [comment]
推荐文章: [初探 Webpack 性能优化](https://aliennnnnn.github.io/2018/12/20/webpack-per/)
推荐理由: Webpack是现在主流的功能强大的模块化打包工具，在使用Webpack时，如果不注意性能优化，有非常大的可能会产生性能问题.
