### ISSUE TITLE
第四十四期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#50]
## 第四十四期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by MonkeyInWind0** [comment]
网址：命令行提示工具 navi https://www.jianshu.com/p/dce764d2835e
投稿理由：命令太多记不住，这里有提示
投稿人：Monid Pei
是否个人: 是

**Comment by akitsukiWong** [comment]
网址：你未必知道的49个CSS知识点    https://juejin.im/post/5d3eca78e51d4561cb5dde12
投稿理由：大多数人对css的学习都比较浅显基础。这篇文章中介绍了很多冷门但实用的 CSS 技巧，并且每个属性都有动图演示，看一遍就能学习到很多，有点意思。
投稿人：Zoe.Wang
是否个人: 否

**Comment by akitsukiWong** [comment]
网址：你未必知道的CSS知识点（第二季） https://juejin.im/post/5d9ec8b0518825651b1dffa3
投稿理由：理由同上，第二季
投稿人：Zoe.Wang
是否个人: 否

**Comment by G-Grant** [comment]
* 网址：[深入理解Mobx](https://juejin.im/post/5c815ebf5188257ded10cec7)
* 投稿理由：这篇文章对于理解mobx的核心原理有很大帮助
* 投稿人：Barret Ge
 * 是否个人: 否

**Comment by G-Grant** [comment]
* 网址：[MobX 背后的基础原理](https://juejin.im/post/5ae808b76fb9a07aad174f5e)
* 投稿理由：不久之前 Bertalan Miklos 写了一篇很好的博文，比较了 MobX 和基于 proxy 的 NX-framework。这篇博文不仅证明了 proxy 的可行性，更好之处在于其触及了 MobX 中一些非常基础但通常又被隐藏的概念。迄今为止我还尚未详细阐述过这些概念，所以本文将分享一些 MobX 特性背后的心路历程。
* 投稿人：Barret Ge
 * 是否个人: 否

**Comment by G-Grant** [comment]
* 网址：[Mobx 源码分析 - array](https://g-grant.github.io/mobx-source-analysis/20191013.html#%E5%89%8D%E8%A8%80)
* 投稿理由：这篇文章会让你知道为什么可监听的数组有 1000 个长度
* 投稿人：Barret Ge
 * 是否个人: 是

**Comment by yomizhong** [comment]
网址：[模拟表单提交进行post方式数据传递](https://yomizhong.github.io/2019/10/14/window-open%E6%A8%A1%E6%8B%9F%E8%A1%A8%E5%8D%95%E6%8F%90%E4%BA%A4%E8%BF%9B%E8%A1%8C%E6%95%B0%E6%8D%AE%E4%BC%A0%E9%80%92/#more)
投稿理由：使用window.open来打开一个新窗口，但是由于地址栏的参数长度限制，当有很大的数据需要交互时，就不能通过地址栏传参，这个时候可以通过模拟form表单提交post方式传值。
投稿人：Yomi Zhong
是否个人：是

**Comment by yomizhong** [comment]
网址：[阿里云OSS文件下载](https://yomizhong.github.io/2019/10/14/OSS%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD/#more)
投稿理由：我们把文件上传到oss上，会得到一个链接，访问链接就可是获取到文件，当我们希望访问文件链接（通过点击事件触发）后可以直接下载文件，改如何实现呢？
投稿人：Yomi Zhong
是否个人：是
