### ISSUE TITLE
第四十五期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#52]
## 第四十五期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by yomizhong** [comment]
网址；[关于edm邮件--那些认真踩过的坑](https://yomizhong.github.io/2019/10/17/%E5%85%B3%E4%BA%8Eedm%E9%82%AE%E4%BB%B6-%E9%82%A3%E4%BA%9B%E8%AE%A4%E7%9C%9F%E8%B8%A9%E8%BF%87%E7%9A%84%E5%9D%91/#more)
投稿理由：本文分享在制作edm邮件过程中，遇到的一些问题及解决方案
投稿人：Yomi Zhong
是否个人：是
