### ISSUE TITLE
第四十六期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#54]
## 第四十六期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by yomizhong** [comment]
网址：[Next.js初探](https://yomizhong.github.io/2019/10/23/next-js%E5%88%9D%E6%8E%A2/)
投稿理由：这是一款轻量级的服务器端渲染框架，使用next.js做SSR是一件很简单的事！
投稿人：Yomi Zhong
是否个人；是
