### ISSUE TITLE
第四十九、五十期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#55]
## 第四十九期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by lichangwei** [comment]
网址：[SWR](https://swr.now.sh/)
投稿理由：SWR 是一个用来获取远程数据的 React Hooks，它的名字来自`stale-while-revalidate`，而`stale-while-revalidate`是[RFC 5861](https://tools.ietf.org/html/rfc5861)提出的一种缓存失效策略。SWR 可以使得在页面页面渲染时先使用旧的数据渲染页面，同时发送请求获取新数据，然后再使用新的数据渲染页面。非常适用于一些数据很少修改，性能要求较高，数据准确性不敏感的情况。
投稿人：Louis Li
是否个人: 否

**Comment by lichangwei** [comment]
网址：[年报系列分享之关键帧动画篇](https://lichangwei.github.io/2019/11/10/annual-report-animation/)
投稿理由：这篇文章主要介绍了通过CSS3实现动画的两种方式transition和animation，简单介绍了transition的用法和局限，重点介绍了animation的用法，特别提示大家的是animation-delay可以是负值，并且有大用。
投稿人：Louis Li
是否个人: 是

**Comment by lichangwei** [comment]
网址：[年报系列分享之工具篇](https://lichangwei.github.io/2019/11/22/annual-report-tools/)
投稿理由：这篇文章主要介绍我们在开发年报项目时用到的一些工具和方法。包括前端工程师如何了解动画细节，以及通过Chrome检查动画效果以及性能。
投稿人：Louis Li
是否个人: 是

**Comment by yomizhong** [comment]
网址：[webp图片知多少](https://yomizhong.github.io/2019/12/06/webp%E7%9F%A5%E5%A4%9A%E5%B0%91/)
投稿理由：相同图片质量的情况下，webp格式的图片要比png和jpg格式要小的多
投稿人：Yomi Zhong
是否个人：是
