### ISSUE TITLE
第五十一期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#56]
## 第五十一期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by MonkeyInWind0** [comment]
网址：https://www.jianshu.com/p/5460695661b6
投稿理由：通过一个模拟登录的demo了解fultter的几个简单的Widget、状态以及路由传参
投稿人：Monid Pei
是否个人: 是
