### ISSUE TITLE
第五十二期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#57]
## 第五十二期在下面回复
**请务必填写投稿人**

## 投稿格式

* 网址：XX
* 投稿理由：XX
* 投稿人：XX（比如：Bar Sui）
 * 是否个人: 是

**Comment by yomizhong** [comment]
网址：[node+jsdom爬虫入门](https://yomizhong.github.io/2019/12/22/node-jsdom%E7%88%AC%E8%99%AB%E5%85%A5%E9%97%A8/)
投稿理由：本文分享使用node+jsdom爬取网络小说，并引入cli-progress进行爬取进度监控
投稿人：Yomi Zhong
是否个人：是
