### ISSUE TITLE
第六期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#6]
第六期在下面回复

**Comment by kingller** [comment]
网址：[你真的了解回流和重绘吗?](https://mp.weixin.qq.com/s/MdY0hIMVE73SEQ2CSU9mbQ)
投稿理由：这篇文章可以帮助我们理解浏览器回流和重绘，以及如何优化浏览器渲染

**Comment by lichangwei** [comment]
网址：[打造高效的 macOS 开发环境 - 添加打印机](https://mp.weixin.qq.com/s/ceXpPWbHHwO8rw88xB7zYg)
投稿理由：这是“打造高效的 macOS 开发环境”系列文章的第一篇，讲述免驱动在 macOS 安装打印机。《飞鹰走码》是我刚刚开始维护的公众号，欢迎大家关注。

**Comment by lichangwei** [comment]
网址：[通过 Proxy 揭秘 JavaScript 的连续赋值](https://mp.weixin.qq.com/s/OXy8-HB63K5DTozlCIPDeg)
投稿理由：相信很多都看到过 JavaScript 连续赋值面试题的解读文章，在本文中我们不去猜测，而是通过 Proxy 来揭示这一过程，你将会得到一个意想不到的结论。
