### ISSUE TITLE
第七期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#7]
第七期在下面回复

**Comment by maningXu** [comment]
推荐文章：https://www.jianshu.com/p/3020740561a8
推荐理由：git版本回退，以后大胆删除代码，再也不用一段逻辑，两份代码，一份注释，一份运行。

**Comment by kingller** [comment]
推荐文章：[如何在github上创建个人项目的在线演示demo](https://segmentfault.com/a/1190000008425992)
推荐理由：在github上搜索相关项目时会发现，有的项目不光写了一手好文档并且还给出了项目的在线运行Demo。事实胜于雄辩，一个在线演示可能给项目带来更好的印象分。如何在github上维护自己个人项目源代码的同时生成在线演示demo呢？

**Comment by zhuchuanlei** [comment]
推荐文章: [你的JavaScript依赖库可能并不安全](https://mp.weixin.qq.com/s/6aLLho6dy_rcHoGSXp1wSg)
推荐理由: 开源的库会提高开发者的工作效率，但它也可能存在一些风险，那应该怎么抉择的？请看这篇文章。

**Comment by caojing1126** [comment]
推荐文章: [调用百度地图API，实现两种效果](https://www.jianshu.com/p/fddab8a4f2fc)
推荐理由: 本篇文章通过调用百度地图API实现了两个效果：第一个是标注位于地图中心点不动，拖动地图实时显示地图中心位置的10个具体地址；第二个效果是实现根据关键字搜索具体地址的功能。
