### ISSUE TITLE
第九期

### ISSUE THREAD

**Issue by G-Grant** [bee-fe/FE-Weekly#9]
## 第九期 ( 2019-01-02 / 2019-01/06 )

> 第九期在下面回复。

**Comment by fansgithub** [comment]
网址：https://fansgithub.github.io/2019/01/02/instanceof/
投稿理由：instanceof的判断原理
投稿人：kasa.fan

**Comment by kingller** [comment]
网址：[Why review code?](https://sophiebits.com/2018/12/25/why-review-code.html)
投稿理由：为什么做代码审查很有价值？大多数硅谷的科技公司都会对每一个变更进行代码审查，以至少让两组人关注它。

**Comment by kingller** [comment]
网址：[2018 JavaScript 现状调查报告火热出炉！](https://mp.weixin.qq.com/s/NWdoywa-NPoaZfPTZpYvNg)
投稿理由：StateOfJS 刚刚发布了 2018年的 JavaScript 现状调查报告，今年他们调查了超过 20000 名 JavaScript 开发者，以确定他们正在使用什么，他们对什么感到满意以及他们想要学习什么。

**Comment by lichangwei** [comment]
网址：[通过一个案例了解 nginx 重载过程](https://lichangwei.github.io/2019/01/05/nginx-reload-failed-without-error/)
投稿理由：回顾一个让我怀疑人生的问题解决过程，让你对 nginx 重载过程多了解一些。

**Comment by beenle-xiaojie** [comment]
网址: [ js编码和解码 ](https://beenle-xiaojie.github.io/2019/01/06/encode-decode/)
投稿理由: js中的编码和解码方法,来更多的了解一些
